auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Joshua's blog.com
url: http://joshuastray.github.io
feed: /atom.xml
author_info: <a href="http://joshuastray.github.io/">Joshua</a>
